### ISSUE TITLE
[BUG] Number keeps getting logged out

### ISSUE THREAD

**Issue by kj2222** [iamrony777/Baileys#10]
Title: When we scan QR code number gets logged in for 2-3 seconds and then again gets logged out
Description:
Sudddenly since yesterday, some of our numbers are getting logged out as soon as we scan QR code:

connection update {
connection: 'close',
lastDisconnect: {
error: Error: Stream Errored (restart required)
at WebSocketClient. (/Users/a/Documents/GitHub/Baileysfinal/src/Socket/socket.ts:662:7)
at WebSocketClient.emit (node:events:518:28)
at WebSocketClient.emit (node:domain:488:12)
at /Users/a/Documents/GitHub/Baileysfinal/src/Socket/socket.ts:338:23
at Object.decodeFrame (/Users/a/Documents/GitHub/Baileysfinal/src/Utils/noise-handler.ts:176:5)
at WebSocketClient.onMessageReceived (/Users/a/Documents/GitHub/Baileysfinal/src/Socket/socket.ts:310:9)
at WebSocketClient.emit (node:events:518:28)
at WebSocketClient.emit (node:domain:488:12)
at WebSocket. (/Users/a/Documents/GitHub/Baileysfinal/src/Socket/Client/web-socket-client.ts:40:52)
at WebSocket.emit (node:events:518:28) {
data: [Object],
isBoom: true,
isServer: true,
output: [Object]
},
date: 2024-05-11T19:52:34.215Z
}
}

**Comment by iamrony777** [comment]
I'll be honest, I had the same problem last week but it solved automatically. But I'll advise to setup a redis and mongo db (use online one's, they are free) and run the example.ts file.

Possible reason: I was logging in and logging off too frequently, like in every 10-20min, as I was debugging a program, and suddenly I saw I can't log in anymore 😂

```bash
git clone https://github.com/iamrony777/Baileys
cd Baileys
npm install
# setup .env
npm run example
```

Let me know if you still get the same error, cause last night I checked and then updated my [npm package](https://www.npmjs.com/package/@iamrony777/baileys)
