### ISSUE TITLE
[BUG] MongoDB

### ISSUE THREAD

**Issue by leroyanders** [iamrony777/Baileys#11]
```
{"level":30,"time":"2024-08-18T12:29:52.184Z","pid":46358,"hostname":"Leroys-MacBook-Air.local","class":"baileys","histNotification":{"fileSha256":"BjQJwHiFj7IG1ld6G4Cu8IPtW570yZyioxaPTSzSIXM=","fileLength":"725","mediaKey":"nvJR4Gdla/zyzpbveMXw4JsPh5a9j3XbetXxHHoAYYI=","fileEncSha256":"JYISukyVIirEorVdptt+6kz35RftDe5SxyO7vaAWBXc=","directPath":"/v/t62.31111-24/25615297_1043747260696680_7550874819352896515_n.enc?ccb=11-4&oh=01_Q5AaIKwwW6jq7rDordsUtYsQncINw3cPO-5km1WbO6CLWgzj&oe=66E96199&_nc_sid=5e03e0","syncType":"PUSH_NAME","chunkOrder":1,"progress":100},"process":true,"id":"3ACAE3169FC0A967510E","isLatest":false,"msg":"got history notification"}

/Users/leroyanders/WebstormProjects/thrivestate-whatsapp-service/node_modules/mongodb/src/cmap/connection.ts:409
        callback(new MongoServerError(document));
                 ^
MongoServerError: ns not found
    at Connection.onMessage (/Users/leroyanders/WebstormProjects/thrivestate-whatsapp-service/node_modules/mongodb/src/cmap/connection.ts:409:18)
    at MessageStream.<anonymous> (/Users/leroyanders/WebstormProjects/thrivestate-whatsapp-service/node_modules/mongodb/src/cmap/connection.ts:239:56)
    at MessageStream.emit (node:events:520:28)
    at processIncomingData (/Users/leroyanders/WebstormProjects/thrivestate-whatsapp-service/node_modules/mongodb/src/cmap/message_stream.ts:193:12)
    at MessageStream._write (/Users/leroyanders/WebstormProjects/thrivestate-whatsapp-service/node_modules/mongodb/src/cmap/message_stream.ts:74:5)
    at writeOrBuffer (node:internal/streams/writable:570:12)
    at _write (node:internal/streams/writable:499:10)
    at MessageStream.Writable.write (node:internal/streams/writable:508:10)
    at Socket.ondata (node:internal/streams/readable:1007:22)
    at Socket.emit (node:events:520:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)

```

my implementation:

```
private async reauthorizeClient(
    user: User,
    socket: SocketWithEvents,
    server: ServerWithEvents,
  ): Promise<any> {
    const clientId = this.baileysEventsService.getClientId(user.id);
    const mongo = new MongoClient(
      `${this.configService.get<string>('MONGO_URL')}_${clientId}`,
      {
        socketTimeoutMS: 1_00_000,
        connectTimeoutMS: 1_00_000,
        waitQueueTimeoutMS: 1_00_000,
      },
    );
    const authCollection = mongo
      .db(
        `${this.configService.get<string>(
          'MONGO_INITDB_DATABASE',
        )}_${clientId}`,
      )
      .collection(`auth`);
    const { state, saveCreds } = await useMongoDBAuthState(authCollection);
    const store: IExtendedStore = makeMongoStore({
      db: mongo.db(
        `${this.configService.get<string>(
          'MONGO_INITDB_DATABASE',
        )}_${clientId}`,
      ),
      autoDeleteStatusMessage: false,
    });

    const client: BaileysClientSocket = makeWASocket({
      auth: {
        creds: state.creds,
        keys: makeCacheableSignalKeyStore(state.keys),
      },
      version: [2, 3000, 1014080102],
      printQRInTerminal:
        this.configService.get<string>('NODE_ENV') === ENodeEnvironment.LOCAL,
      syncFullHistory: false,
      shouldSyncHistoryMessage: () => true,
      fireInitQueries: false,
      generateHighQualityLinkPreview: true,
      getMessage: this.getMessage,
      browser: Browsers.ubuntu('Chrome'),
      waWebSocketUrl: 'wss://web.whatsapp.com/ws/chat',
      msgRetryCounterCache: this.msgRetryCounterCache,
    });

    store.bind(client.ev);

    this.clients.delete(clientId);
    this.clients.set(clientId, client);

    this.getMessage = async (
      key: WAMessageKey,
    ): Promise<WAMessageContent | undefined> => {
      if (store) {
        const msg = await store.loadMessage(key.remoteJid, key.id);
        return msg?.message || undefined;
      }
      return proto.Message.fromObject({});
    };

    client.ev.on('creds.update', saveCreds);

    this.setupListeners(client, user, server, store, socket);
    return client;
  }
```

I got this, which mongodb version are you using?

**Comment by iamrony777** [comment]
Are you still facing the same issue?

**Comment by iamrony777** [comment]
Reason: No activity
